config/routes.rb
Rails.application.routes.draw do
  devise_for :users, only: :omniauth_callbacks,
              controllers: {omniauth_callbacks: "omniauth_callbacks"}

  scope "(:locale)", locale: /en|vi/ do
    root "static_page#home"
    devise_for :users, skip: :omniauth_callbacks
    as :user do
      get "signin" => "devise/sessions#new"
      post "signin" => "devise/sessions#create"
      delete "signout" => "devise/sessions#destroy"
    end
    resources :products, only: [:show]
    resources :orders, only: [:new, :create]
    namespace :admin do
      root "static_pages#index"
      resources :orders, only: [:index, :edit, :update]
      resources :products
      get :order_status, to: "static_pages#order_status"
      get :order_total_money_month, to: "static_pages#order_total_money_month"
      get :order_total_money_quarter, to: "static_pages#order_total_money_quarter"
      get :order_total_money_year, to: "static_pages#order_total_money_year"
      get :order_accept_month, to: "static_pages#order_accept_month"
      get :order_accept_quarter, to: "static_pages#order_accept_quarter"
      get :order_accept_year, to: "static_pages#order_accept_year"
    end

    resources :carts, only: [:index] do
      collection do
        get "/add_to_cart/:id", to: "carts#add_to_cart", as: "add_to"
        get "remove/:id", to: "carts#remove_from_cart", as: "remove_from"
        put "update_cart/:id", to: "carts#update_cart", as: "update"
      end
    end

  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :find_product,
                :get_line_item,
                :check_residual_quantity?,
                only: [:add_to_cart, :remove_from_cart, :update_cart]
  before_action :authenticate_user!
  authorize_resource class: false

  def index
    @cart_items = get_line_items_in_cart
  end

  def add_to_cart
    if @item
      @item["quantity"] += params[:quantity].to_i
      flash[:info] = t "flash.cart_update"
    else
      current_cart << {
        product_id: @product.id, quantity: params[:quantity].to_i
      }
      flash[:success] = t "flash.cart_success"
    end
    session[:cart] = current_cart
    redirect_to product_path
  end

  def remove_from_cart
    if @item
      flash[:success] = t "flash.remove_cart_success"
      current_cart.delete(@item)
    else
      flash[:danger] = t "flash.remove_cart_fail"
    end
    redirect_to carts_path
  end

  def update_cart
    if @item
      @item["quantity"] = params[:quantity].to_i
      flash.now[:success] = t "flash.update_cart_success"
    else
      flash[:danger] = t "flash.update_cart_fail"
    end
    redirect_to carts_path
  end

  private

  def check_residual_quantity?
    quantity = if @item
                 @item["quantity"] + params[:quantity].to_i
               else
                 params[:quantity].to_i
               end
    return if @product.check_residual_quantity? quantity

    flash[:danger] = t "flash.not_enough"
    redirect_to root_path
  end

  def get_line_item
    @item = find_product_in_cart @product
  end
end

app/helpers/carts_helper.rb
module CartsHelper
  def current_cart
    session[:cart] ||= Array.new
  end

  def find_product_in_cart product
    current_cart.find{|item| item["product_id"] == product.id}
  end

  def get_line_items_in_cart
    cart_items = []
    current_cart.each do |item|
      product = Product.find_by(id: item["product_id"])
      if product
        cart_items << {product: product, quantity: item["quantity"]}
      else
        current_cart.delete(item)
      end
    end
    cart_items
  end

  def line_total_price item
    item[:product].price * item[:quantity]
  end

  def total_of_money
    items = get_line_items_in_cart
    items.reduce(0){|a, e| a + e[:product].price * e[:quantity]}
  end
end

app/views/carts/index.html.erb
<% provide(:title, t("pages.cart")) %>
<div class="cart_page">
  <div class="container cart_height">
    <table id="cart" class="table table-hover table-condensed">
      <thead>
        <tr>
          <th style="width:50%"><%= t "pages.product_name" %></th>
          <th style="width:10%"><%= t "pages.price" %></th>
          <th style="width:8%"><%= t "pages.quantity" %></th>
          <th style="width:22%" class="text-center"><%= t "pages.actual_price" %></th>
          <th style="width:10%"> </th>
        </tr>
      </thead>
      <tbody>
        <% @cart_items.reverse! %>
        <% @cart_items.each do |item| %>
          <tr>
            <td>
              <div class="row">
                <div class="col-sm-2 hidden-xs">
                  <img src="/assets/computer.jpg" alt="Sản phẩm 1" class="img-responsive" width="100">
                </div>
                <div class="col-sm-10">
                  <h4 class="product_name"><%= item[:product].name %></h4>
                </div>
              </div>
            </td>
            <td class="product_price"><%= number_to_currency_format item[:product].price %></td>
            <%= form_with(url: update_carts_path(item[:product]), local: false, method: :put) do |f| %>
              <td class="quantity">
                <%= f.number_field :quantity, value: item[:quantity], min: 1, class: "form-control text-center change-quatity"%>
                <%= f.hidden_field :id, value: item.dig(:product)&.id, class: "cart_product_id" %>
              </td>
            <% end %>
            <td data-th="subtotal" class="text-center"><%= number_to_currency_format line_total_price(item) %></td>
            <td class="actions">
              <%= link_to remove_from_carts_path(item[:product]), class: "btn btn-warning btn-block" do %>
                <%= t "pages.remove" %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
      <tfoot>
        <tr>
          <td>
            <a href="#" class="btn btn-info">
              <i class="fa fa-angle-left"></i> <%= t "pages.continue_buy" %>
            </a>
          </td>
          <td colspan="2" class="hidden-xs"> </td>
          <td class="hidden-xs text-center">
            <strong>
              <%= t "pages.total_of_money" %> <%= number_to_currency_format total_of_money %>
            </strong>
          </td>
          <td>
            <%= link_to new_order_path, class: "btn btn-success btn-block" do %>
              <%= t "pages.pay" %> <i class="fa fa-angle-right"></i>
            <% end %>
          </td>
        </tr>
      </tfoot>
    </table>
  </div>
</div>
<%= javascript_include_tag "ajax_cart" %>