config/routes.rb
Rails.application.routes.draw do
  devise_for :users, only: :omniauth_callbacks,
              controllers: {omniauth_callbacks: "omniauth_callbacks"}

  scope "(:locale)", locale: /en|vi/ do
    root "static_page#home"
    devise_for :users, skip: :omniauth_callbacks
    as :user do
      get "signin" => "devise/sessions#new"
      post "signin" => "devise/sessions#create"
      delete "signout" => "devise/sessions#destroy"
    end
    resources :products, only: [:show]
    resources :orders, only: [:new, :create]
    namespace :admin do
      root "static_pages#index"
      resources :orders, only: [:index, :edit, :update]
      resources :products
      get :order_status, to: "static_pages#order_status"
      get :order_total_money_month, to: "static_pages#order_total_money_month"
      get :order_total_money_quarter, to: "static_pages#order_total_money_quarter"
      get :order_total_money_year, to: "static_pages#order_total_money_year"
      get :order_accept_month, to: "static_pages#order_accept_month"
      get :order_accept_quarter, to: "static_pages#order_accept_quarter"
      get :order_accept_year, to: "static_pages#order_accept_year"
    end

    resources :carts, only: [:index] do
      collection do
        get "/add_to_cart/:id", to: "carts#add_to_cart", as: "add_to"
        get "remove/:id", to: "carts#remove_from_cart", as: "remove_from"
        put "update_cart/:id", to: "carts#update_cart", as: "update"
      end
    end

  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :order_details, dependent: :destroy
  has_many :rates, dependent: :destroy
  accepts_nested_attributes_for :category, allow_destroy: true
  has_one_attached :image

  ransack_alias :product, :name_or_description

  scope :product_order, ->(field){order field}
  scope :searchs, ->(keywrd){where("products.name LIKE ? or products.description LIKE ?", "%#{keywrd}%", "%#{keywrd}%")}

  validates :image,
            content_type:
            {
              in: Settings.admin.product.image.format,
              message: I18n.t("products.image_format_message")
            },
            size:
            {
              less_than: Settings.admin.product.image.less_than.megabytes,
              message: I18n.t("products.image_format_size")
            }

  validates :name,
            presence: true,
            length: {maximum: Settings.product.max_length_name}

  validates :price,
            presence: true

  validates :discount,
            presence: true,
            length: {in: Settings.product.min_discount..Settings.product.max_discount}

  validates :residual,
            presence: true,
            length: {maximum: Settings.product.max_residual}

  validates :description,
            presence: true

  def check_residual_quantity? quantity_params
    quantity_params.positive? && residual >= quantity_params
  end

  def display_image
    image.variant resize_to_limit: [Settings.admin.product.image.width, Settings.admin.product.image.height]
  end

  def display_image_200
    image.variant resize_to_limit: [Settings.admin.product.image.width_200, Settings.admin.product.image.height_200]
  end

  ransacker :created_at, type: :date do
    Arel.sql("date(products.created_at)")
  end

  def self.ransackable_attributes auth_object = nil
    if auth_object == :admin
      super
    else
      super & %w(product name description price created_at)
    end
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::BaseController
  before_action :fetch_product, only: [:show, :edit, :update, :update_product_category_condition?, :destroy]
  authorize_resource

  def index
    @products = if search_params?
                  search_with_sort params[:search], params[:option]
                else
                  Product.all
                end.page(params[:page]).per(Settings.size.page_record_medium)
  end

  def new
    @product = Product.new
    @product.build_category
  end

  def create
    @product = if add_category_condition?
                 Product.new product_category_params
               else
                 Product.new product_params
               end
    if @product.save
      flash[:success] = t "products.add_success"
      redirect_to admin_products_url
    else
      flash[:danger] = t "products.add_failed"
      render :new
    end
  end

  def show; end

  def edit; end

  def update
    if update_product_category_condition?
      update_product_category @product, product_category_params
    else
      update_product_category @product, product_params
    end
  end

  def destroy
    if @product&.destroy
      flash[:success] = "delete_success"
    else
      flash[:danger] = "delete_failed"
    end
    redirect_to admin_products_url
  end

  private

  def update_product_category product, params
    if product.update params
      flash[:success] = "updated_success"
      redirect_to admin_products_url
    else
      render :edit
    end
  end

  def fetch_product
    @product = Product.find_by id: params[:id]
    return if @product

    flash[:danger] = "error_not_find"
    redirect_to admin_products_path
  end

  def update_product_category_condition?
    name_equal = @product.category.name != product_category_params[:category_attributes][:name]
    id_equal = product_params[:category_id].to_i == @product.category_id
    name_equal && id_equal
  end

  def add_category_condition?
    product_category_params[:category_attributes][:name].present?
  end

  def search_params?
    params[:search] && params[:option]
  end

  def search_with_sort search_keyword, option
    search_product = Product.searchs(search_keyword)
    settings = Settings.admin.product_option
    @products = case option
                when settings.oldest
                  search_product.product_order :updated_at
                when settings.newest
                  search_product.product_order updated_at: :desc
                when settings.price
                  search_product.product_order :price
                when settings.price_desc
                  search_product.product_order price: :desc
                else
                  Product.all
                end
  end

  def product_params
    params.require(:product)
          .permit(
            :name, :price, :image, :discount, :residual, :description, :category_id
          )
  end

  def product_category_params
    params.require(:product)
          .permit(
            :name, :price, :image, :discount, :residual, :description,
            category_attributes: [:name, :parent_id]
          )
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :fetch_product, only: [:show, :rating, :check_user_rated_product?]

  def show
    @rates = Rate.rate_product(params[:id])
    @existed_rate = Rate.check_user_rate(current_user.id, @product.id).first if check_user_rated_product?
  end

  def rating
    if current_user
      rate = Rate.new
      rate.rating = params[:rate_num]
      rate.content = ""
      rate.user_id = current_user.id
      rate.product_id = @product.id
      save_or_update_rating rate
      flash[:success] = t "rating.rating_success"
    else
      flash[:danger] = t "rating.rating_failed"
    end
    respond_to do |format|
      format.html{redirect_to @product}
      format.js
    end
  end

  private

  def save_or_update_rating rate
    if check_user_rated_product?
      @existed_rate = Rate.check_user_rate(rate.user_id, rate.product_id).first
      @existed_rate.update_column :rating, params[:rate_num]
    else
      rate.save
    end
  end

  def check_user_rated_product?
    Rate.check_user_rate(current_user.id, @product.id).present? if current_user
  end

  def fetch_product
    @product = Product.find_by id: params[:id]
    return if @product.present?

    flash[:danger] = t "flash.not_found_product"
    redirect_to root_url
  end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
  def create_index params_page, index
    per_page = Settings.size.page_record_medium
    params_page = 1 if params_page.nil?
    (params_page.to_i - 1) * per_page.to_i + index.to_i + 1
  end
end

app/helpers/products_helper.rb
module ProductsHelper
  def rated num, user_rated_product
    if user_rated_product && (num + 1) <= user_rated_product.rating.to_i
      "checked"
    else
      ""
    end
  end
end

app/views/admin/products/_category_fields.html.erb
<%= f.label :name , "category name"%>
<%= f.text_field :name, class: "category-name" %>
<%= f.label :parent_id , "parent_id"%>
<%= f.collection_select :parent_id, Category.all, :id, :name, {},{:class=>"form-control" }%>
<div>
  <p class="remove-fields mx-3 text-primary" style="cursor: pointer;"><%= t "products.use_existed_category" %>use existed categories</p>
</div>
<br>

app/views/admin/products/_form.html.erb
<div class="col-md-6 col-md-offset-3">
  <%= form_for [:admin, @product] do |f|%>
    <%= render "shared/error_messages", object: f.object %>
    <div>
      <%= f.label t "products.name" %>
      <%= f.text_field :name, class: "form-control" %>
    </div>
    <div>
      <%= f.label t "products.price" %>
      <%= f.text_field :price, class: "form-control" %>
    </div>
    <div>
      <span class="image">
        <%= f.label t "products.image" %>
        <%= f.file_field :image, accept: "image/jpeg,image/gif,image/png" %>
      </span>
    </div>
    <div>
      <%= f.label t "products.discount" %>
      <%= f.text_field :discount, class: "form-control" %>
    </div>
    <div>
      <%= f.label t "products.residual" %>
      <%= f.text_field :residual, class: "form-control" %>
    </div>
    <div>
      <%= f.label t "products.description" %>
      <%= f.text_field :description, class: "form-control" %>
    </div>
    <div class="lable-form category-existed">
      <%= f.label :category_id, "category" %>
      <%= f.collection_select :category_id, Category.all, :id, :name,
      {},{:class=>"form-control"}%>
    </div>
    <div>
      <h5 class="add-category-toggle alert alert-success" style="cursor: pointer"><%= t "products.add_new_category" %></h5>
      <fieldset class="add-category-fs">
        <%= f.fields_for :category do |category_form| %>
          <%= render "category_fields", f: category_form %>
        <% end %>
        <div class="link-to-add-fields">
          <%= link_to_add_fields t("products.add_new_category"), f, :category %>
        </div>
      </fieldset>
    </div>
    <div class="submit-form-index">
      <%= f.submit t("products.add_new"), class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/admin/products/_form_search_filter.html.erb
<%= form_tag(admin_products_path, :method => "get", id: "search-form", class:"form-inline form-group") do %>
  <%= text_field_tag :search, params[:search], placeholder: t("orders.find_placeholder"), class: "form-control mr-sm-2" %>
  <%= submit_tag t("admin.search"), class: "btn bg-primary my-2 my-sm-0" %>
  <span class="status-title"><%= t "orders.filter_by" %></span>
  <%= select_tag :option, options_for_select(Settings.admin.product_sorts, params[:option]), class: "form-control mr-sm-2" %>
  <%= link_to t("products.add_new"),  new_admin_product_path, class: "btn btn-primary", style: "margin-left: 20px;" %>
<% end %>

app/views/admin/products/_product.html.erb
<% @products.each_with_index do |product, index| %>
  <tr>
    <td><%= create_index params[:page], index %></td>
    <td><%= product.name %></td>
    <td><%= number_to_currency_format product.price %></td>
    <td><%= product.discount %></td>
    <td><%= product.residual %></td>
    <td><%= product.description %></td>
    <td><%= image_tag product.display_image if product.image.attached? %></td>
    <td>
      <%= link_to admin_product_path(product) do %>
        <i class="fa fa-2x fa-eye text-primary" aria-hidden="true"></i>
      <% end %>
      <%= link_to edit_admin_product_path(product) do %>
        <i class="fa fa-2x fa-pencil-square-o text-success" aria-hidden="true"></i>
      <% end %>
      <%= link_to admin_product_path(product), method: :delete, data: {confirm: t("admin.confirm_delete")} do %>
        <i class="fa fa-2x fa-window-close text-danger" aria-hidden="true"></i>
        <% end %>
      </td>
  </tr>
<% end %>

app/views/admin/products/_thead_product.html.erb
<tr>
  <th><%= t "products.id" %></th>
  <th><%= t "products.name" %></th>
  <th><%= t "products.price" %></th>
  <th><%= t "products.discount" %></th>
  <th><%= t "products.residual" %></th>
  <th><%= t "products.description" %></th>
  <th><%= t "products.image" %></th>
  <th class="col-md-2"><%= t "products.action" %></th>
</tr>

app/views/admin/products/edit.html.erb
<% provide(:title, t("products.add_new_title")) %>
<h4 class="container text-info">
  <%= t "products.add_new_title" %>
</h4>
<%= render "form" %>

app/views/admin/products/index.html.erb
<% provide :title, t("products.admin_title") %>
<section class="panel important">
  <h2><%= t "admin.products" %></h2>
</section>
<div class="container">
  <%= render "form_search_filter" %>
</div>
<div class="table-responsive">
  <table class="table">
    <thead>
      <%= render "thead_product" %>
    </thead>
    <tbody>
      <%= render "product" %>
    </tbody>
  </table>
</div>
<div>
  <%= paginate @products %>
</div>

app/views/admin/products/new.html.erb
<% provide(:title, t("products.add_new_title")) %>
<h4 class="container text-info">
  <%= t "products.add_new_title" %>
</h4>
<%= render "form" %>

app/views/admin/products/show.html.erb
<% provide(:title, t("orders.details_title")) %>
<div class="container">
  <h2><%= t "orders.details_title" %></h2>
  <table class="table">
    <thead>
      <tr>
        <th><%= t "orders.details_name" %></th>
        <th><%= t "orders.details_desc" %></th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <th><%= t "products.id" %></th>
        <td><%= @product.id %></td>
      </tr>
      <tr>
        <th><%= t "products.name" %></th>
        <td><%= @product.name %></td>
      </tr>
      <tr>
        <th><%= t "products.price" %></th>
        <td><%= number_to_currency_format @product.price %></td>
      </tr>
      <tr>
        <th><%= t "products.discount" %></th>
        <td><%=  @product.discount %></td>
      </tr>
      <tr>
        <th><%= t "products.residual" %></th>
        <td><%= @product.residual %></td>
      </tr>
      <tr>
        <th><%= t "products.category" %></th>
        <td><%= @product.category.name %></td>
      </tr>

      <tr>
        <th><%= t "products.description" %></th>
        <td><%= @product.description %></td>
      </tr>
      <tr>
        <th><%= t "products.image" %></th>
        <td><%= image_tag @product.display_image_200 if @product.image.attached? %></td>
      </tr>
    </tbody>
  </table>
  <div class="container">
    <%= link_to "back", admin_products_path, class: "btn btn-success" %>
  </div>
</div>