config/routes.rb
Rails.application.routes.draw do
  devise_for :users, only: :omniauth_callbacks,
              controllers: {omniauth_callbacks: "omniauth_callbacks"}

  scope "(:locale)", locale: /en|vi/ do
    root "static_page#home"
    devise_for :users, skip: :omniauth_callbacks
    as :user do
      get "signin" => "devise/sessions#new"
      post "signin" => "devise/sessions#create"
      delete "signout" => "devise/sessions#destroy"
    end
    resources :products, only: [:show]
    resources :orders, only: [:new, :create]
    namespace :admin do
      root "static_pages#index"
      resources :orders, only: [:index, :edit, :update]
      resources :products
      get :order_status, to: "static_pages#order_status"
      get :order_total_money_month, to: "static_pages#order_total_money_month"
      get :order_total_money_quarter, to: "static_pages#order_total_money_quarter"
      get :order_total_money_year, to: "static_pages#order_total_money_year"
      get :order_accept_month, to: "static_pages#order_accept_month"
      get :order_accept_quarter, to: "static_pages#order_accept_quarter"
      get :order_accept_year, to: "static_pages#order_accept_year"
    end

    resources :carts, only: [:index] do
      collection do
        get "/add_to_cart/:id", to: "carts#add_to_cart", as: "add_to"
        get "remove/:id", to: "carts#remove_from_cart", as: "remove_from"
        put "update_cart/:id", to: "carts#update_cart", as: "update"
      end
    end

  end
end

app/views/admin/layouts/_footer_admin.html.erb
<footer role="contentinfo"><%= t "admin.footer" %></footer>

app/views/admin/layouts/_header_admin.html.erb
<header role="banner">
  <h1 class="warn"><%= t "pages.title" %></h1>
  <ul class="utilities">
    <li><%= link_to t("pages.vi"), locale: :vi %></li>
    <li><%= link_to t("pages.en"), locale: :en %></li>
    <li class="users"><%= link_to t("pages.profile"), "#" %></li>
    <li class="logout warn"> <%= link_to t("pages.logout"), signout_path, method: :delete %></li>
  </ul>
</header>

app/views/admin/layouts/_nav_admin.html.erb
<nav class="nav_admin" role="navigation">
  <ul class="main">
    <li class="dashboard"><%= link_to t("admin.dashboard"), admin_root_path %></li>
    <li class="write"><%= link_to t("admin.orders"), admin_orders_path %></li>
    <li class="edit"><%= link_to t("admin.products"), admin_products_path %></li>
    <li class="comments"><%= link_to t("admin.categories"), "#" %></li>
    <li class="users"><%= link_to t("admin.users"), "#" %></li>
  </ul>
</nav>

app/views/admin/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title yield :title %></title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
  <%= javascript_pack_tag "application", "data-turbolinks-track": "reload" %>
</head>

<body>
  <%= render "admin/layouts/header_admin" %>
  <%= render "admin/layouts/nav_admin" %>
  <main role="main">
    <% flash.each do |message_type, message| %>
      <div class="flash-alert text-center alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
  </main>
  <%= render "admin/layouts/footer_admin" %>
  <%= javascript_pack_tag "custom", "data-turbolinks-track": "reload" %>
</body>
</html>