config/routes.rb
Rails.application.routes.draw do
  devise_for :users, only: :omniauth_callbacks,
              controllers: {omniauth_callbacks: "omniauth_callbacks"}

  scope "(:locale)", locale: /en|vi/ do
    root "static_page#home"
    devise_for :users, skip: :omniauth_callbacks
    as :user do
      get "signin" => "devise/sessions#new"
      post "signin" => "devise/sessions#create"
      delete "signout" => "devise/sessions#destroy"
    end
    resources :products, only: [:show]
    resources :orders, only: [:new, :create]
    namespace :admin do
      root "static_pages#index"
      resources :orders, only: [:index, :edit, :update]
      resources :products
      get :order_status, to: "static_pages#order_status"
      get :order_total_money_month, to: "static_pages#order_total_money_month"
      get :order_total_money_quarter, to: "static_pages#order_total_money_quarter"
      get :order_total_money_year, to: "static_pages#order_total_money_year"
      get :order_accept_month, to: "static_pages#order_accept_month"
      get :order_accept_quarter, to: "static_pages#order_accept_quarter"
      get :order_accept_year, to: "static_pages#order_accept_year"
    end

    resources :carts, only: [:index] do
      collection do
        get "/add_to_cart/:id", to: "carts#add_to_cart", as: "add_to"
        get "remove/:id", to: "carts#remove_from_cart", as: "remove_from"
        put "update_cart/:id", to: "carts#update_cart", as: "update"
      end
    end

  end
end

app/controllers/admin/static_pages_controller.rb
class Admin::StaticPagesController < Admin::BaseController
  authorize_resource class: false

  def index; end

  def order_status
    render json: Order.group(:status).size
  end

  def order_total_money_month
    render json: Order.group_by_month(:created_at).sum(:total_of_money)
  end

  def order_total_money_quarter
    render json: Order.group_by_quarter(:created_at).sum(:total_of_money)
  end

  def order_total_money_year
    render json: Order.group_by_year(:created_at).sum(:total_of_money)
  end

  def order_accept_month
    render json: Order.accept.group_by_month(:created_at).size
  end

  def order_accept_quarter
    render json: Order.accept.group_by_quarter(:created_at).size
  end

  def order_accept_year
    render json: Order.accept.group_by_year(:created_at).size
  end
end

app/controllers/static_page_controller.rb
class StaticPageController < ApplicationController
  def home
    @categories = Category.by_category
    @brands = Category.by_brand
    @q = Product.joins(:category).ransack(params[:q], auth_object: set_ransack_auth_object)
    @products = @q.result.page(params[:page]).per(Settings.size.page_record_medium).product_order :price
  end

  def set_ransack_auth_object
    current_user&.admin? ? :admin : nil
  end
end

app/views/admin/static_pages/index.html.erb
<section class="panel important">
  <h2><%= t "chartkick.welcome_dashboard" %> </h2>
  <div id="content">
    <div class="container-fluid">
      <h3><%= t "chartkick.each_status" %></h3>
        <%= pie_chart admin_order_status_path %>
    </div>
    <div class="container-fluid">
      <div class="row">
        <h3><%= t "chartkick.money_month" %></h3>
        <%= line_chart admin_order_total_money_month_path, thousands: ",", suffix: " vnđ" %>
      </div>
      <div class="row">
        <h3><%= t "chartkick.money_quarter" %></h3>
        <%= line_chart admin_order_total_money_quarter_path, thousands: ",", suffix: " vnđ" %>
      </div>
      <div class="row">
        <h3><%= t "chartkick.money_year" %></h3>
        <%= line_chart admin_order_total_money_year_path, thousands: ",", suffix: " vnđ" %>
      </div>
    </div>
    <div class="container-fluid">
      <div class="row">
        <h3><%= t "chartkick.order_month" %></h3>
        <%= column_chart admin_order_accept_month_path %>
      </div>
      <div class="row">
        <h3><%= t "chartkick.order_quarter" %></h3>
        <%= column_chart admin_order_accept_quarter_path %>
      </div>
      <div class="row">
        <h3><%= t "chartkick.order_year" %></h3>
        <%= column_chart admin_order_accept_year_path %>
      </div>
    </div>
  </div>
</main>